version: "3"

services:
  ikarus:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DOMAIN_ADDRESS=$DOMAIN_ADDRESS
    entrypoint: [ "/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh" ]
    command: [ "./main" ]
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ikarus.rule=Host(`$DOMAIN_ADDRESS`)"
      - "traefik.http.routers.ikarus.entrypoints=web,websecure"
      - "traefik.http.routers.ikarus.tls.certresolver=myresolver"
networks:
  web:
    external: true
  postgres-network:
    driver: bridge
