version: "3"

services:
  ikarus:
    build:
      context: .
      dockerfile: Dockerfile.vps
    environment:
      - ENVIRONMENT=$ENVIRONMENT
      - DB_SOURCE=$DB_SOURCE
      - HTTP_SERVER_ADDRESS=$HTTP_SERVER_ADDRESS
      - TOKEN_SYMMETRIC_KEY=$TOKEN_SYMMETRIC_KEY
      - DOMAIN=$DOMAIN
    entrypoint: [ "/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh" ]
    command: [ "./main" ]
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ikarus.rule=Host(`$DOMAIN`)"
      - "traefik.http.routers.grafana.entrypoints=web,websecure"
      - "traefik.http.routers.grafana.tls.certresolver=myresolver"
networks:
  web:
    external: true
