name: Deploy

on:
  push:
    branches:
      - main  # Deploy on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ikarus.arrow-silver.com

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: executing remote ssh commands
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.VPS_IP }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd /root/projects/ikarus || exit
          git checkout main
          git pull origin main
          cd ../traefik || exit
          sudo docker-compose -f docker-compose-vps.yml down
          sudo docker-compose -f docker-compose-vps.yml build --no-cache
          sudo ENVIRONMENT=release DB_SOURCE=${{ secrets.DB_SOURCE }} HTTP_SERVER_ADDRESS=${{ secrets.HTTP_SERVER_ADDRESS }} TOKEN_SYMMETRIC_KEY=${{ secrets.TOKEN_SYMMETRIC_KEY }} DOMAIN=${{ secrets.DOMAIN }} docker-compose -f docker-compose-vps.yml up -d
